/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-zxing.h
 #	source generated by 4D Plugin Wizard
 #	Project : zxing
 #	author : miyako
 #	2022/06/06
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_ZXING_H
#define PLUGIN_ZXING_H

/* Must come before anything that might pull in <windows.h> (including
   4DPluginAPI.h below): <windows.h> auto-includes the old Winsock 1.1
   <winsock.h> unless WIN32_LEAN_AND_MEAN is already defined, and once that's
   happened, any later <winsock2.h>/<ws2tcpip.h> include (from the project's
   Windows compat headers) conflicts with it — duplicate struct/function
   definitions across the whole file. Including <winsock2.h> first here wins
   that race unconditionally. Gated on the compiler-provided _WIN32 rather
   than the SDK's own VERSIONMAC/VERSIONWIN, since those aren't defined yet
   at this point in the file. */
#ifdef _WIN32
#define WIN32_LEAN_AND_MEAN
#include <winsock2.h>
#endif

#include "4DPluginAPI.h"

#include "DecodeHints.h"
#include "Result.h"
#include "ReadBarcode.h"
#include "BarcodeFormat.h"
#include "ImageView.h"

#include <algorithm>

#if VERSIONMAC
#import <Accelerate/Accelerate.h>
#import <AVFoundation/AVFoundation.h>
#import <ImageIO/ImageIO.h>
#else
#ifndef max
#define max(a,b) (((a) > (b)) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) (((a) < (b)) ? (a) : (b))
#endif
#include <shlwapi.h>
#include <gdiplus.h>
#endif

#include "4DPlugin-JSON.h"

#include "C_TEXT.h"

/* zxing decode() is declared threadSafe in manifest.json. stb_image keeps its
   last-error string (stbi__g_failure_reason) in a plain global unless
   STBI_THREAD_LOCAL is defined before the header is included, which would be
   a data race under concurrent calls. This code doesn't currently read that
   global, so it's not a live bug, but defining this is free insurance and a
   no-op if this vendored stb_image.h doesn't use the macro. */
#ifndef STBI_THREAD_LOCAL
#define STBI_THREAD_LOCAL thread_local
#endif

#include <stb_image.h>

#pragma mark -

void zxing_decode(PA_PluginParameters params);

#endif /* PLUGIN_ZXING_H */
