/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-zxing.h
 #	source generated by 4D Plugin Wizard
 #	Project : zxing
 #	author : miyako
 #	2022/06/06
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_ZXING_H
#define PLUGIN_ZXING_H

#include "4DPluginAPI.h"

#include "DecodeHints.h"
#include "Result.h"
#include "ReadBarcode.h"
#include "BarcodeFormat.h"
#include "ImageView.h"

#include <algorithm>

#if VERSIONMAC
#import <Accelerate/Accelerate.h>
#import <AVFoundation/AVFoundation.h>
#import <ImageIO/ImageIO.h>
#else
#ifndef max
#define max(a,b) (((a) > (b)) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) (((a) < (b)) ? (a) : (b))
#endif
#include <shlwapi.h>
#include <gdiplus.h>
#endif

#include "4DPlugin-JSON.h"

#include "C_TEXT.h"

#include <stb_image.h>

#pragma mark -

void zxing_decode(PA_PluginParameters params);

#endif /* PLUGIN_ZXING_H */
